---
kind: pipeline
name: Ubuntu 22.04 - CODE COVERAGE
steps:
  - name: codecov
    image: bobicloudvision/drone-codecov:latest
    environment:
      CODECOV_TOKEN:
          from_secret: CODECOV_TOKEN
    settings:
      token: $CODECOV_TOKEN
      files:
        - /usr/local/phyre/web/clover.xml
      flags:
        - unit
