---
kind: pipeline
name: Docker - Quick Test
steps:
  - name: run
    image: bobicloudvision/phyre-panel:latest
    environment:
      DEBIAN_FRONTEND: noninteractive
    commands:
      - MAIN_REPO_DIR=$(pwd)
      - apt-get install -y rsync
      - cp /usr/local/phyre/web/phyre-config.ini  /usr/local/phyre/phyre-config.ini.bak
      - rm -rf /usr/local/phyre/web
      - cp -r $MAIN_REPO_DIR/web /usr/local/phyre/web
      - cp /usr/local/phyre/phyre-config.ini.bak /usr/local/phyre/web/phyre-config.ini
      - cd /usr/local/phyre/web/
      - ls -la 
      - wget https://getcomposer.org/download/latest-stable/composer.phar
      - COMPOSER_ALLOW_SUPERUSER=1 phyre-php composer.phar install
      - phyre-php artisan test
