kind: pipeline
steps:
  - name: Phyre Panel - Install Base
    image: ubuntu:22.04
    commands:
      - apt-get install -y libicu-dev libzip-dev libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libxml2-dev libcurl4-openssl-dev libssl-dev libpq-dev libsqlite3-dev libxslt1-dev libzip-dev libbz2-dev libreadline-dev libedit-dev libpspell-dev libenchant-dev libgmp-dev libldap2-dev libldb-dev libldap2-dev libldap-2.4-2
      - ls -la

      - mkdir /phyre-panel
      - cp installers/ubuntu-22.04/install-partial/install_base.sh /phyre-panel/install_base.sh
      - chmod +x /phyre-panel/install_base.sh
      - /phyre-panel/install_base.sh
      - cp installers/ubuntu-22.04/install-partial/install_web.sh /phyre-panel/install_web.sh
      - chmod +x /phyre-panel/install_web.sh

      - cp -r web /usr/local/phyre/web/
      - cd /usr/local/phyre/web/
      - wget https://getcomposer.org/download/latest-stable/composer.phar
      - COMPOSER_ALLOW_SUPERUSER=1 phyre-php composer.phar install
      - /phyre-panel/install_web.sh
      - phyre-php artisan test
