---
kind: pipeline
name: CentOS
steps:
  - name: run unit tests
    image: centos:latest
    commands:
      - sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
      - sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      - yum update -y
      - dnf -y install sudo wget
      - sudo wget -q -O - http://www.atomicorp.com/installers/atomic | sh

      - mkdir /phyre-panel
      - cp installers/centos-stream-9/install-partial/install_base.sh /phyre-panel/install_base.sh
      - chmod +x /phyre-panel/install_base.sh
      - /phyre-panel/install_base.sh

---
kind: pipeline
name: Debian 12
steps:
  - name: run unit tests
    image: debian:12
    environment:
      DEBIAN_FRONTEND: noninteractive
    commands:
      - apt-get update
