services:
  phyre:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
        - "80:80"
        - "443:443"
        - "3306:3306"
        - "8443:8443"
    volumes:
      - .:/usr/local/phyre

