<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class CronJob extends Model
{
    protected $fillable = [
        'schedule',
        'command',
        'user',
    ];

    public static function boot()
    {
        parent::boot();

        static::created(function ($model) {
            $model->configureCronJobs();
        });

        static::updated(function ($model) {
            $model->configureCronJobs();
        });

        static::deleted(function ($model) {
            $model->configureCronJobs();
        });
    }
    public function configureCronJobs()
    {
        $getAll = self::all();
        if ($getAll->count() > 0) {
            $users = [];
            foreach ($getAll as $cron) {
                $users[$cron->user][] = $cron->toArray();
            }
            foreach ($users as $user => $cronJobs) {
                $now = now();
                $cronContent = <<<EOT
                # PhyrePanel Cron Jobs
                # User: $user
                # Generated at: $now
                # Do not edit this file manually, it is automaticly generated by PhyrePanel
                EOT;
                $cronContent .= PHP_EOL . PHP_EOL;

                foreach ($cronJobs as $cronJob) {
                    $cronContent .= $cronJob['schedule'] . ' ' . $cronJob['command'] . PHP_EOL;
                }

                $cronContent .= PHP_EOL;
                $cronFile = '/tmp/crontab-' . $user;
                file_put_contents($cronFile, $cronContent);

                $output = shell_exec('crontab -u ' . $user . ' ' . $cronFile);
                unlink($cronFile);

            }
        }

        return false;
    }

}
