services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: {{$containerName}}
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: {{$hostName}}
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "110:110"  # POP3
      - "995:995"  # POP3 (with TLS)
    volumes:
      - {{$workPath}}/docker-data/dms/mail-data/:/var/mail/
      - {{$workPath}}/docker-data/dms/mail-state/:/var/mail-state/
      - {{$workPath}}/docker-data/dms/mail-logs/:/var/log/mail/
      - {{$workPath}}/docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - {{$workPath}}/docker-data/acme-companion/certs/:/etc/letsencrypt/live/:ro

    environment:
      - SSL_TYPE=letsencrypt
      - VIRTUAL_HOST={{$hostName}}
      - LETSENCRYPT_HOST={{$hostName}}
      - ENABLE_FAIL2BAN=0
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      - SPOOF_PROTECTION=0
      - ENABLE_POP3=1
      - POSTMASTER_ADDRESS=postmaster@localhost.localdomain
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
