name: Phyre Panel - Code Coverage

on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-coverage-phyre-web-panel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
      - name: Npm install
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, dom, fileinfo, mysql, gd, curl, zip, sqlite, xml,
          coverage: xdebug

      - name: Install Composer Dependencies
        working-directory: ./web
        run: |
          composer install
          composer dump-autoload

      - name: Install NODE Dependencies
        working-directory: ./web
        run: |
          npm install
          npm run build
      - name: Run Code Coverage
        working-directory: ./web
        run: composer test:coverage
      - name: Code Cov
        working-directory: ./web
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: clover.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
